# Generated by Django 4.2.2 on 2023-07-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'student'},
        ),
        migrations.AddField(
            model_name='student',
            name='prefix',
            field=models.IntegerField(choices=[(1, 'นาย'), (2, 'นางสาว'), (3, 'นาง')], default=1),
        ),
    ]
